### ISSUE TITLE
Initial ssh commands require interactively saying 'yes'

### ISSUE THREAD

**Issue by aleks-mariusz** [prabhatsharma/kubernetes-the-hard-way-aws#18]
The first time one connects to a host that ssh has not previously seen the host-key for, it asks you to manually confirm.  There's an ssh option that can be used the first time to automatically add this thus making these commands more non-interactive.   Of course disabling host key checking like this should not typically be done lightly, however since these are transient/temporary hosts, it shouldn't be very big of a risk.

Will create a PR to enable this, and allow you to decide whether this is an acceptable trade-off for the sake of making the commands easier to run w/o having to interactive with them as much.

**Comment by prabhatsharma** [comment]
Thanks for sending the PRs. I have merged the others. I would like to leave this one. This adds a little more abstraction. Since this is a learning exercise, I would like to avoid another layer of abstraction and some of the people wondering and trying to figure out how the magic worked and spending time figuring it out. Let me know if you think otherwise.

**Comment by aleks-mariusz** [comment]
Understood and i get where you're coming from.. it becomes quite easy to just copy/paste your way to a kubernetes cluster and takes the 'hard' part ouf the name of this project..  i'll close this issue out then and cancel my PR..
